version: "3"

services:
  db-postgres:
    image: postgres:alpine
    ports:
      - "5433:5432"
    container_name: "db-postgres"
    restart: always
    volumes:
      - ./banco-de-dados-financeapp:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: mydb

volumes:
  banco-de-dados-eventos:
