version: "3"

services:
  db-postgres:
    image: postgres:alpine
    ports:
      - ${PGPORT}
    container_name: "db-postgres"
    restart: always
    volumes:
      - ./banco-de-dados-financeapp:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}

volumes:
  banco-de-dados-finaceapp:
